version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.10.1
    steps:
      - checkout

      - restore_cache:
          keys: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npm run test
